on: [push]
name: Run

jobs:
  main:
    runs-on: ubuntu-latest
    name: Badge
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Launch the local action
        uses: shadowmoose/GHA-LoC-Badge@1.0.0 
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge.svg
          ignore: 'README'

      - name: Print the output
        run: |
          echo "Scanned: ${{ steps.badge.outputs.counted_files }}";
          echo "Line Count: ${{ steps.badge.outputs.total_lines }}";